### ISSUE TITLE
Support creating new ID/name node with mixed types (int/string) for $idname and $type

### ISSUE THREAD

**Issue by ingo-budde** [cubiclesoft/php-winpefile#5]
The WinPEFile.CreateResourceIDNameNode() method adds a new node to the directory entries and either provides a name, if $idname is a string, or else it provides an id, if $idname is an integer (see [here](https://github.com/cubiclesoft/php-winpefile/blob/master/support/win_pe_file.php#L1555)).

Providing a the $idname as string (to use it as name, instead of id) does not currently work, if the $type is provided as integer (which should be unrelated to the type of $name in my understanding).

This functionality is provided in pull request #4.

**Comment by cubiclesoft** [comment]
Fixed by merged pull request.  Closing.
