### ISSUE TITLE
Can all values in `VS_VERSION_INFO` be modified?

### ISSUE THREAD

**Issue by bilogic** [cubiclesoft/php-winpefile#8]
Since `VS_VERSION_INFO` is returned as an array, I'm on the impression that all values can be modified.
However, that does not seem to be the case. Fields such as `LegalCopyright`, `LegalTrademarks` can't seem to update.

On a side note, after the PE has been modified, it cannot be parsed again by `WinPEUtils::GetVersionResource(...)`.

This is the exception I get:

```
   ErrorException 

  Undefined index: strings

  at vendor/cubiclesoft/to-composer/src/WinPEUtils.php:329
    325▕                         if (! isset($entry['string_tables'][$result['key']])) {
    326▕                             $entry['string_tables'][$result['key']] = [];
    327▕                         }
    328▕ 
  ➜ 329▕                         $entry['string_tables'][$result['key']] += $result['entry']['strings'];
    330▕ 
    331▕                         ksort($entry['string_tables'][$result['key']]);
    332▕                     }
    333▕                 }
```

**Comment by bilogic** [comment]
Pardon me, `LegalCopyright` and `LegalTrademarks` are updating correctly now. Must have been some cache.

**Comment by bilogic** [comment]
The exception has gone away too. Really unsure what happened there. Thank you.

**Comment by cubiclesoft** [comment]
I'm unsure what happened as well.  If you are able to replicate again, please update the issue with additional details.  Pretty strange behavior for it to throw an exception but then start working.

The only thing I can think of is:

```php
			else if ($parentkey === "StringFileInfo" && strlen($key) == 8)
```

Where the `$key` is not 8 bytes long would cause the "strings" array to not be returned.  But that would violate Microsoft's spec:

https://docs.microsoft.com/en-us/windows/win32/menurc/stringtable
